[project]
name = "dl-bioinf"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "torch (>=2.6.0+cpu,<3.0.0+cpu) ; extra != 'cuda'",
    "torchvision (>=0.21.0+cpu) ; extra != 'cuda'",
    "lightning (>=2.5.1.post0,<3.0.0)",
    "hydra-core (>=1.3.2,<2.0.0)",
    "tensorboard (>=2.19.0,<3.0.0)",
    "pandas (>=2.2.3,<3.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "jupyter (>=1.1.1,<2.0.0)",
    "notebook (>=7.4.1,<8.0.0)",
    "torch-geometric (>=2.6.1,<3.0.0)",
    "torch-scatter (>=2.1.2,<3.0.0) ; extra != 'cuda'",
    "torch-sparse (>=0.6.18,<0.7.0) ; extra != 'cuda'",
    "torch-cluster (>=1.6.3,<2.0.0) ; extra != 'cuda'",
]

[project.optional-dependencies]
cuda = [
    "torch (>=2.6.0+cu126,<3.0.0+cu126)",
    "torchvision (>=0.21.0+cu126)",
    #"lightning (>=2.5.1.post0,<3.0.0)",
    #"torch-scatter (>=2.1.2+cu126,<3.0.0+cu126)",
    #"torch-sparse (>=0.6.18+cu126,<0.7.0+cu126)",
    #"torch-cluster (>=1.6.3+cu126,<2.0.0+cu126)",
]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
# python = "^3.10"
torch = [
    { markers = "extra != 'cuda'", source = "pytorch-cpu"},
    { markers = "extra == 'cuda'", source = "pytorch-cuda"},
]
torchvision = [
    { markers = "extra != 'cuda'", source = "pytorch-cpu"},
    { markers = "extra == 'cuda'", source = "pytorch-cuda"},
]
# https://github.com/python-poetry/poetry/issues/9191
torch-scatter = [
    {platform = "linux", markers = "extra != 'cuda'", source = "pyg-cpu"},
    {platform = "linux", markers = "extra == 'cuda'", source = "pyg-cuda"},
    {platform = "darwin", python = "3.10", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_scatter-2.1.2-cp310-cp310-macosx_10_9_universal2.whl"},
    {platform = "darwin", python = "3.11", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_scatter-2.1.2-cp311-cp311-macosx_10_9_universal2.whl"},
    {platform = "darwin", python = "3.12", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_scatter-2.1.2-cp312-cp312-macosx_10_13_universal2.whl"},
]
torch-cluster = [
    {platform = "linux", markers = "extra != 'cuda'", source = "pyg-cpu"},
    {platform = "linux", markers = "extra == 'cuda'", source = "pyg-cuda"},
    {platform = "darwin", python = "3.10", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_cluster-1.6.3-cp310-cp310-macosx_10_9_universal2.whl"},
    {platform = "darwin", python = "3.11", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_cluster-1.6.3-cp311-cp311-macosx_10_9_universal2.whl"},
    {platform = "darwin", python = "3.12", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_cluster-1.6.3-cp312-cp312-macosx_10_13_universal2.whl"},
]
torch-sparse = [
    {platform = "linux", markers = "extra != 'cuda'", source = "pyg-cpu"},
    {platform = "linux", markers = "extra == 'cuda'", source = "pyg-cuda"},
    {platform = "darwin", python = "3.10", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_sparse-0.6.18-cp310-cp310-macosx_11_0_universal2.whl"},
    {platform = "darwin", python = "3.11", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_sparse-0.6.18-cp311-cp311-macosx_11_0_universal2.whl"},
    {platform = "darwin", python = "3.12", url = "https://data.pyg.org/whl/torch-2.6.0%2Bcpu/torch_sparse-0.6.18-cp312-cp312-macosx_11_0_universal2.whl"},
]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[[tool.poetry.source]]
name = "pyg-cuda"
url = "https://data.pyg.org/whl/torch-2.6.0+cu126.html"
priority = "explicit"

[[tool.poetry.source]]
name = "pyg-cpu"
url = "https://data.pyg.org/whl/torch-2.6.0+cpu.html"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
priority = "explicit"

[[tool.poetry.source]]
name = "pytorch-cuda"
url = "https://download.pytorch.org/whl/cu126"
priority = "explicit"
